name: CI
on: [push]
env:
  SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}

jobs:
  ci:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup with node16.15
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16.15'

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test

      - name: Success
        uses: rtCamp/action-slack-notify@v2.2.0
        if: success()
        env:
          SLACK_TITLE: Passed tests
          SLACK_COLOR: good

      - name: Failure
        uses: rtCamp/action-slack-notify@v2.2.0
        if: failure()
        env:
          SLACK_TITLE: Failed tests
          SLACK_COLOR: danger

      - name: Cancel
        uses: rtCamp/action-slack-notify@v2.2.0
        if: cancelled()
        env:
          SLACK_TITLE: Canceled tests
          SLACK_COLOR: danger
