name: CI Workflow for Vercel

on: [push]

env:
  SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}

jobs:
  ci:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: cd ${{ github.workspace }} && yarn install && yarn test

      - name: Success
        uses: rtCamp/action-slack-notify@v2.2.0
        if: success()
        env:
          SLACK_TITLE: Success
          SLACK_COLOR: good

      - name: Failure
        uses: rtCamp/action-slack-notify@v2.2.0
        if: failure()
        env:
          SLACK_TITLE: Failure
          SLACK_COLOR: danger

      - name: Cancel
        uses: rtCamp/action-slack-notify@v2.2.0
        if: cancelled()
        env:
          SLACK_TITLE: Cancel
          SLACK_COLOR: danger
